const playList = [
  {
		id: '1',
		artist: 'Crazy P',
		originalArtist: 'Crazy P',
    title: 'Heartbreaker',
		url: 'https://od.lk/s/ODBfMjgwMTYyMTJf/Crazy_P_Heartbreaker.mp3',
		cover: 'https://od.lk/s/ODBfMjgxMTU4Nzdf/crazy_p_heartbreaker.jpg',
		text: ['ля-ля-ля', 'три рубля'],
		video: 'https://www.youtube.com/watch?v=Ph5psMQoirU',
  },
	{
		id: '2',
		artist: 'The Eighty Eight',
		originalArtist: 'Crazy P',
    title: 'Fish Tank',
		url: 'https://od.lk/s/ODBfMjgwMTYyMjZf/Fish_Tank_The_Eighty_Eight.mp3',
		cover: 'https://od.lk/s/ODBfMjgxMTU5MDZf/the_eighty_eight_fishtank.jpg',
		text: ['ля-ля-ля', 'пять рубля'],
		video: 'https://www.youtube.com/watch?v=Ctvx5glcAO8',
  },
	{
		id: '3',
		artist: 'Freedom Satellite',
		originalArtist: 'Crazy P',
    title: 'Astro Black (The Big Wow Mix)',
		url: 'https://od.lk/s/ODBfMjgwMTYyMzFf/Freedom%20Satellite%20-%20Astro_Black_%28The_Big_Wow_Mix%29.mp3',
		cover: 'https://od.lk/s/ODBfMjgxMTYwMDhf/freedom_satellite_astro_black.jpg',
		text: ['ля-ля-ля', 'два рубля'],
		video: 'https://www.youtube.com/watch?v=Syv1xj0vvPw',
  },
	{
		id: '4',
		artist: 'Jabbar',
		originalArtist: 'Crazy P',
    title: 'RAF (Deeperise & Tolgah Remix)',
		url: 'https://od.lk/s/ODBfMjgwMTYyMzJf/Jabbar_RAF_%28Deeperise_%26_Tolgah_Remix%29.mp3',
		cover: 'https://od.lk/s/ODBfMjgxMTYwMTZf/jabbar_deeprise.jpeg',
		text: 'Я помню чудное мнгновенье\nПередо мной явилась ты',
		video: false,
  },
	{
		id: '5',
		artist: 'Shpongle',
		originalArtist: 'Crazy P',
    title: 'Grand Piano and Flute Concerto',
		url: 'https://od.lk/s/ODBfMjgwMTYyMzNf/Shpongle_Grand_Piano_and_Flute_Concerto.mp3',
		cover: 'https://od.lk/s/ODBfMjgxMTYwMjFf/shpongle_grand_piano_and_flute_concerto.jpeg',
		text: ['ля-ля-ля', 'ноль рубля'],
		video: false,
  },
]

export default playList;
